### ISSUE TITLE
tutorial with require.js integration

### ISSUE THREAD

**Issue by webuniverseio** [rickbeerendonk/ReactJS.NET-getting-started-tutorial#1]
Hi @rickbeerendonk, I [created a require.js integration example](https://github.com/szarouski/ReactJS.NET-with-require.js-getting-started-tutorial) based on current tutorial code. Just wanted to let you know. Thank you.

**Comment by rickbeerendonk** [comment]
@szarouski Cool! I will have a closer look as soon as I am back at my Windows machine.
